- name: Install Python 3.10
  ansible.builtin.apt:
    name: python3.10
    state: present
  become: true
  become_method: sudo
  become_user: root
  tags: [packages, install, python]

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: true
  become_method: sudo
  become_user: root
  tags: [packages, install, pip]

- name: Install pipenv
  ansible.builtin.pip:
    name: pipenv
    state: present
  become: true
  become_method: sudo
  become_user: root
  tags: [packages, install, pipenv]
