---  # Adapted from https://github.com/geerlingguy/ansible-role-security/blob/master/tasks/autoupdate-Debian.yml
- name: Install unattended upgrades package
  ansible.builtin.package:
    name: unattended-upgrades
    state: present
  tags: [packages, updates]

- name: Copy unattended-upgrades configuration files in place.
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - 10periodic
    - 50unattended-upgrades
  tags: [update, unattended, upgrades, configuration]
