---
- name: Update package cache and upgrade packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 3600
    autoremove: true
    autoclean: true
    state: present
  tags: [packages, update]

- name: Install essential packages
  ansible.builtin.package:
    name: "{{ essential_packages }}"
    state: present
  tags: [packages, install, essential]
