---
- name: Ensure groups are present
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - sudo
    - docker

- name: Create non-root user "{{ username }}"
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    shell: /bin/bash
    createhome: true
    home: "/home/{{ username }}"
    groups:
      - sudo
      - docker
    append: true
    update_password: on_create
    state: present
  become: true
  become_user: root
  become_method: sudo
  tags: [user, create]

- name: Enable passwordless sudo for "{{ username }}"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
    validate: "/usr/sbin/visudo -cf %s"
    state: present
  become: true
  become_user: root
  become_method: sudo
  tags: [sudo, passwordless, authentication]
