---
- name: Install fail2ban package
  ansible.builtin.package:
    name: fail2ban
    state: present
  become: true
  become_user: root
  become_method: sudo
  tags: [fail2ban, security, packages]

- name: Copy fail2ban jail configuration file
  ansible.builtin.template:
    src: fail2ban.conf.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  become: true
  become_user: root
  become_method: sudo
  tags: [fail2ban, security, configuration]
